### ISSUE TITLE
Vysor App on mac crashes on load

### ISSUE THREAD

**Issue by andy-pi** [koush/vysor.io#1256]
This bug has appear with Vysor on Mac, v5.0.7 released today. Every time Vysor is opened it displays this error, it opens afterwards but causes a problem for me (sometimes loads the safe mode).
Unfortunately each time I revert to an old version Vysor auto updates. Please can you fix or let us roll back to an old version without updating! Thank you!!

Uncaught Exception:
Error: write EPIPE
at afterWriteDispatched (node:internal/stream_base_commons:160:15)
at writeGeneric (node:internal/stream_base_commons:151:3)
at Socket._writeGeneric (node:net:930:11)
at Socket._write (node:net:942:8)
at writeOrBuffer (node:internal/streams/writable:392:12)
at _write (node:internal/streams/writable:333:10)
at Writable.write (node:internal/streams/writable:337:10)
at console.value (node:internal/console/constructor:300:16)
at console.log (node:internal/console/constructor:377:26)
at createWindow (/Applications/Vysor.app/Contents/Resources/app.asar/dist_electron/bundled/main/

**Comment by iamscottweber** [comment]
Yeah same issue here. vysor -s [serial] on cli is not working.

**Comment by koush** [comment]
investigating

**Comment by koush** [comment]
@andy-pi are you opening via cli or just via the application launcher?

**Comment by koush** [comment]
A screenshot and full log of the error would be helpful too. Not sure where you're seeing this?

**Comment by iamscottweber** [comment]
When opening a specific device with 'vysor s [serial]' vysor has the same error and then opens in 'Safe Mode' .

![image](https://github.com/koush/vysor.io/assets/32939092/c9cad089-1ca3-449b-9022-225ab7c5a80b)

**Comment by andy-pi** [comment]
![Screenshot 2023-05-18 at 18 03 59](https://github.com/koush/vysor.io/assets/11014042/2d26948b-aa5e-48b7-8507-9bbf9fdd8130)
same for me

**Comment by koush** [comment]
Ok to be clear: this bug ONLY happens when launching from CLI? Does it launch normally from the app launcher?

**Comment by andy-pi** [comment]
That's correct, seems to be ok from dock launcher, just cli having the issue

**Comment by koush** [comment]
Should be fixed in latest `vysor-cli`, please confirm.

**Comment by andy-pi** [comment]
I tried just do `npm update vysor` and tested v1.1.2 for the cli tool, but still getting the same issue :-( Anything else I can test?

**Comment by koush** [comment]
npm -g install vysor@latest

**Comment by koush** [comment]
I repro'd the issue and confirmed the fix. fairly certain you need to update the global installation of the CLI tool now. I don't think `npm update vysor` updates the global install.

**Comment by andy-pi** [comment]
I'm still getting the same issue. I'm not familiar at all with npm packing. Is there any cache I might need to flush? 

% npm -g install vysor@latest
/Users/<UNAME>/.npm-global/bin/vysor -> /Users/<UNAME>/.npm-global/lib/node_modules/vysor/dist/bin.js
+ vysor@1.1.2
updated 1 package in 2.646s

**Comment by koush** [comment]
run `which vysor` to see what it points to

**Comment by iamscottweber** [comment]
I install the latest and I'm also still getting an error.  

npm list -g vysor

/Users//.npm-global/lib
└── vysor@1.1.2 


![image](https://github.com/koush/vysor.io/assets/32939092/d622a5a9-7233-48a0-ae71-a83701874959)

**Comment by andy-pi** [comment]
> which vysor points to /usr/local/bin/vysor

same for me

**Comment by koush** [comment]
apple silicon or intel?
output from `node -version`?

**Comment by andy-pi** [comment]
node --version v14.18.0 on x86 for me

**Comment by koush** [comment]
please update to node 18.

**Comment by iamscottweber** [comment]
Updating to node 18 seems to have fixed the issue on my end. Thanks

**Comment by andy-pi** [comment]
updated node  v18.16.0. No change, still throws the error on vysor -a or -d options

**Comment by koush** [comment]
Is this happening from a first launch or vysor already running?

**Comment by andy-pi** [comment]
Only when first launched

**Comment by koush** [comment]
Thanks, I see it now. Let me test further.

**Comment by koush** [comment]
New CLI version and vysor update should fix this.

**Comment by andy-pi** [comment]
So I updated the CLI to v1.1.3 and Vysor itself:
1 x M1 machine - no error, fixed
2 x M1 machines - same error
2 x x86 machines - same error

Thanks for all your work so far @koush

**Comment by koush** [comment]
Can you confirm the vysor versions of the machines that are failing

**Comment by andy-pi** [comment]
yes sure, they are all the same -
app: Pro v 5.0.16 (Runtime 5.0.7)) beta channel; cli: latest, i.e. v1.1.3

**Comment by koush** [comment]
what command are you executing exactly?

**Comment by andy-pi** [comment]
vysor -a; vysor -d; vysor -s [serial]

**Comment by koush** [comment]
is that the single command on the shell?

**Comment by koush** [comment]
Ok I updated the cli tool once more, can you check?

**Comment by iamscottweber** [comment]
I'm still seeing this issue on x86 (Ventura 13.2.1) with ── vysor@1.1.4

![image](https://github.com/koush/vysor.io/assets/32939092/0ba33669-f60a-4789-bd41-d51b8f880c4e)
![image](https://github.com/koush/vysor.io/assets/32939092/bd7eb0d5-96d1-4228-9631-c04e002ccab6)

WORKING: M1 (Ventura 13.0)

**Comment by koush** [comment]
Any chance one of you can give me TeamViewer access to a machine with this issue?

**Comment by iamscottweber** [comment]
I'll talk about it with my team and get back to you today.  We're still having the same issue. Thanks

**Comment by koush** [comment]
@iamscottweber Thanks. I am happy to try to fix it but I'm no longer able to repro with any steps at the moment.

**Comment by iamscottweber** [comment]
Ok, I've gotten the okay to proceed if you're available to remote in.
