### ISSUE TITLE
Phones that do not support screenrecording do not work

### ISSUE THREAD

**Issue by koush** [koush/vysor.io#2]
Phones that do not support "screenrecord" do not work with vysor. This will be fixed in a future version via another screen recording mechanism.

"screenrecord" is a command line tool available in adb shell that comes with most modern devices (kitkat+). If your device is not supported, and this command line tool is not found, please add it to this issue.

**Comment by Alexintosh** [comment]
Apparently the problem is that /system is mounter as read-only

**Comment by koush** [comment]
@Alexintosh that should not matter.

**Comment by koush** [comment]
@Alexintosh this was a bug with root or xposed. i believe this has been fixed in 1038.

**Comment by Alexintosh** [comment]
So do I need root for this?

**Comment by koush** [comment]
no root needed, just update vysor.

**Comment by kalenf** [comment]
Neutab by MediaTek - Device shows only black screen

**Comment by thorpj** [comment]
Reporting issue with Samsung Galaxy S3, with Lollipop custom ROM.

**Comment by fird01** [comment]
Blank screen on galaxy note 2 with CM12.1 rooted
on windows 10 & osx 10.10.5

**Comment by dros74** [comment]
Black screen with Meizu MX5. Mouse and keyboard works, it's just that the phone's screen is not rendered in the vysor window.

**Comment by koush** [comment]
@dros74 what vysor version

**Comment by koush** [comment]
@dros74 does screenrecord work?

**Comment by dros74** [comment]
v1.0.5.2 

``` bash
shell@mx5:/ $ screenrecord test1
screenrecord test1
Unable to open 'test1': Read-only file system
```

**Comment by thorpj** [comment]
@koush Just tested with my S3 on Win10 on 1.0.5.2, Unfortunately the black screen is still there, although as dros74 said, it changes to landscape position correctly.

**Comment by koush** [comment]
@dros74 put the file on your Sdcard, won't be able to write files on the root directory.

```
cd /sdcard
screenrecord test.mp4
```

**Comment by koush** [comment]
@thorpj Please open an issue on github or in this community with the requested info.

https://plus.google.com/u/0/110558071969009568835/posts/1uS4nfW7xhp

**Comment by koush** [comment]
@dros74 Please open an issue on github or this community with the requested info

**Comment by thorpj** [comment]
@koush Done. Apologies, i thought this was just down to the screen record problem on pre kitkat devices, so i thought we'd stick to the one thread.

**Comment by koush** [comment]
Fixed in 1057

**Comment by thorpj** [comment]
@koush Thank you Koush, excellent work.

**Comment by thorpj** [comment]
@koush Unfortunately still not working for me on 1.0.5.7 

See #46 for my info

**Comment by koush** [comment]
@thorpj https://github.com/koush/vysor.io/issues/50

**Comment by thorpj** [comment]
@koush My bad, i assumed that #2 and #50 were the same problem.

**Comment by lkaranam** [comment]
@koush It was really amazing to use Vysor app. I would like to know if there is a way to embed Vysor  screen on PC, into any web application.

**Comment by mr5z** [comment]
Displays "He's dead Jim" icon on KitKat 4.4.2. Probably the location where you streamed the file is read-only

**Comment by amanda10** [comment]
S6 not finding device..

**Comment by zhurai** [comment]
Stock VZW Samsung Galaxy S3 unable to see device. It does have USB Debugging on + I installed the drivers for it too...

**Comment by mostafa1611** [comment]
Hi Dears.
How to run vysor with a selected android device with serial id?
for example, adb devices I get 42f752000cfeafcc and 111152000cfeaeee. I would like to open 111152000cfeaeee from vysor, I would like to automate vysor at some point, any api for scripting ?
Thank you.

**Comment by Knordy** [comment]
Black screen with:
Samsung Galaxy Tab 2 10.1 (GT-P5100)
Android 4.2.2

Windows 10
Vysor Beta 1.0.6.5

**Comment by spupuz** [comment]
have same problem black screen with version 1.0.7.1 ubuntu 16.04 and chrome Version 52.0.2729.3 dev (64-bit) ha no problem before with version 1.0.6.7.
the windows is black and i can click with mouse but i see nothing.

**Comment by tianzhijiexian** [comment]
+1

**Comment by rbaumgar** [comment]
Medion LIFETAB S8312, Android 4.2.2, Vysor 1.0.8.0

Tablet shows blue screen with "Vysor is connected", PC black screen.
Screenrecord works fine with adb...

**Comment by dporem** [comment]
Motorola MC3200 - Android 4.1 - Vysor 1.0.8.8

"No devices found. Make sure Android USB Debugging is enabled."
I can debug on this device and droid@Screen works.

**Comment by githubsrinath** [comment]
Galaxy Tab 2 ( Samsung GT-P3100 Android 4.1.2, API 16) Can NOT render Vysor... Shows Sad smiley screen.  

How to make it work?  Please help

**Comment by manneherrmann** [comment]
LG Optimus G (G970) Can't  access via Vysor. Screen broken and not working.
