### ISSUE TITLE
Error Connecting to Android Device

### ISSUE THREAD

**Issue by aaronxiong1991** [koush/vysor.io#515]
**Describe the bug**
I am trying to "view" the Android 6 device on the Windows Vysor (Free version 3.0.77) application. I have the adb tool set up properly, which I can connect the android device through the IP address. However, when I try to connect/view the android device, it fails and displays the error message:

Error Connecting to Android Device
Error: Request failed with status code 403

**To Reproduce**
1. Open Android Studio Terminal, execute command "adb connect IP-address"
2. Open Vysor, and click on the View button

**Expected behavior**
The Android 6 device screen is mirroring on the Windows Vsyor application

**Screenshots**
![image](https://user-images.githubusercontent.com/31665658/81419361-22f7d300-911c-11ea-98b0-60a2c6fca127.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Vysor Version [Fren Version 3.0.77]

**Android (please complete the following information):**
 - Device: N/A
 - OS: [Android 6]
 - Vysor Bug Report Link: N/A

**Vysor Bug Report**
id 
email 
process.versions {"node":"12.13.0","v8":"8.0.426.27-electron.0","uv":"1.32.0","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"76","nghttp2":"1.39.2","napi":"5","llhttp":"1.1.4","http_parser":"2.8.0","openssl":"1.1.0","icu":"65.1","unicode":"12.1","electron":"8.2.4","chrome":"80.0.3987.165"}
package.json 3.0.77
os win32
electron true
pwa false
https://vysorelectron.clockworkmod.com/#/
enterprise cached check failed Error: not cached
clockwork cached check failed Error: not cached
chromeStore cached check failed Error: not logged in

**Android Logcat**
N/A

**Additional context**
N/A

**Comment by nrpieper** [comment]
I'm experiencing the same issue.  Vysor on Windows 10 v3.0.67.0
When attempting to connect I first see: 
Error: Request failed with status code 403
and then:
Error Connecting to Android Device

**Comment by koush** [comment]
Will take a look

**Comment by koush** [comment]
Can you please generate a bug report that contains the error itself? You need to capture the report after the error happens. Leave the windows open.

**Comment by koush** [comment]
I was unable to reproduce this bug.

**Comment by aaronxiong1991** [comment]
id 
email 
process.versions {"node":"12.13.0","v8":"8.0.426.27-electron.0","uv":"1.32.0","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"76","nghttp2":"1.39.2","napi":"5","llhttp":"1.1.4","http_parser":"2.8.0","openssl":"1.1.0","icu":"65.1","unicode":"12.1","electron":"8.2.4","chrome":"80.0.3987.165"}
package.json 3.0.77
os win32
electron true
pwa false
https://vysorelectron.clockworkmod.com/#/
enterprise cached check failed Error: not cached
clockwork cached check failed Error: not cached
chromeStore cached check failed Error: not logged in

This is the bug report after the issue happened.

**Comment by koush** [comment]
This is an incomplete report. Please just share the gist link instead of pasting it.

**Comment by aaronxiong1991** [comment]
https://gist.github.com/VysorLogs/81178b1a91c77c62796993e8a1a3b7cb

Add-on: I was trying to view the android device via Wifi connection, not connected with micro-USB cable

**Comment by koush** [comment]
@aaronxiong1991 you need to leave the device window open when capturing the report. This is an incomplete report again.

**Comment by koush** [comment]
There's a chance the bug report isn't generating properly, but its a longshot to be honest.

**Comment by koush** [comment]
Are you behind a firewall or vpn or something? The 403 could be happening when attempting to fetch the apk.

**Comment by aaronxiong1991** [comment]
The device window is open, and then I click the bug report button to generate the report.
![image](https://user-images.githubusercontent.com/31665658/81444503-3ff4cc00-9145-11ea-9708-1b5637b5f692.png)

**Comment by koush** [comment]
> Are you behind a firewall or vpn or something? The 403 could be happening when attempting to fetch the apk.

In case you missed it. @aaronxiong1991

**Comment by aaronxiong1991** [comment]
I am actually using VPN, but not sure whether that will cause an issue or not

**Comment by koush** [comment]
Can you confirm this is fixed in 3.0.80?

**Comment by aaronxiong1991** [comment]
It is not fixed yet
![image](https://user-images.githubusercontent.com/31665658/81448659-bf39ce00-914c-11ea-8e08-d27aaa4ea95c.png)
The following is the bug report with the device window open:
https://gist.github.com/VysorLogs/131d1dda3e7a2330004c66bbcbdab371

**Comment by koush** [comment]
@aaronxiong1991 can you launch the vysor.exe with IS_TEST=true
```
IS_TEST=true C:\Program Files...\Vysor.exe
```

This starts vysor with the electron/chromium debugger open.

Then get me the failed network request?

**Comment by aaronxiong1991** [comment]
@koush Is this what you are looking for?
![image](https://user-images.githubusercontent.com/31665658/81449360-1ee4a900-914e-11ea-978c-78ccbfa6af1d.png)

**Comment by koush** [comment]
Thanks, that confirms that there is a firewall/vpn culprit of some sort preventing the download of the apk.

Can you type the following into the javascript console:

```
localStorage.debug = 'vysor,adb';
```

Reload the app using the reload button.
Try again.
Then send me the same logs (which will have more information this time).

**Comment by koush** [comment]
This is the link it is downloading.

https://vysorelectron.clockworkmod.com/Vysor-release.apk

Let me know if that works in your desktop browser.

**Comment by aaronxiong1991** [comment]
@koush, I wish I could reply faster, but it takes some time to reconnect the device. 
What I did, I reconnect the device with the new IP address, then execute the command "set IS_TEST = True" and run the vysor.exe
Then I tried to "view" to reproduce the previous log console information, then I type the "localStorage.debug = 'vysor,adb';" on both open javascript console, then reload the vysor, and try to view. The followings are what I got
![image](https://user-images.githubusercontent.com/31665658/81454038-28bfd980-9159-11ea-9a14-7b961148a784.png)
![image](https://user-images.githubusercontent.com/31665658/81454046-31b0ab00-9159-11ea-9e53-5040c2fe7dc2.png)
![image](https://user-images.githubusercontent.com/31665658/81454062-3aa17c80-9159-11ea-9e02-7f3b7a3dc309.png)

**Comment by aaronxiong1991** [comment]
The link you just sent is blocked/inhibited

**Comment by koush** [comment]
Do you run a virus scanner or something? Somehow, the file doesn't exist in the downloaded install either.

**Comment by aaronxiong1991** [comment]
Let me double check

**Comment by koush** [comment]
Oh, I know why the Windows fallback doesn't work.

If you can find a way to bypass that firewall and install the apk I linked, it will get you going in the meantime.

**Comment by aaronxiong1991** [comment]
I tried the link you post earlier, it is blocked and states that "Threat found: Sandbox Malware"

**Comment by aaronxiong1991** [comment]
After I download the apk file, do I need to push it to the android device?

**Comment by koush** [comment]
Yes, you need to install it.

**Comment by Rufh** [comment]
Hello, i had the same issue, blocking on the installing apk screen when connecting my phone. After installing the apk you given (why is it not the same that the one on play store ?), i can see my phone screen. 
But i found it slow at least 1 second between phone and pc screen even with the fastest parameters sets (bitrate 0.5 Mo/s, decoder hardware).

**Comment by koush** [comment]
New release fixes this by including the apk on Windows and Linux. You may need to download this as i'm not sure if your firewall will detect full updates given that apk is blocked.

https://github.com/koush/vysor.io/releases/tag/v3.0.84
