### ISSUE TITLE
Unable to access Devices via share server

### ISSUE THREAD

**Issue by JonYeeY** [koush/vysor.io#586]
**Describe the bug**
When i connect devices via IP and share the server nobody can open the devices.
Via cable share server work, and when i share the devices lonely it works too

**Screenshots**
![Vysor Error](https://user-images.githubusercontent.com/53002243/87680450-be8d6b80-c77d-11ea-8609-fe33043b0676.png)

**Desktop (please complete the following information):**
 - OS: Windows10 / Ubuntu 18.02
 - Vysor Version Pro 3.0.95

remote candidate [object Object]
got rtc pinger
sending challenge response [object Object]
Checking Vysor APK installation...
Uninstalling older Vysor APK...
[object Object]
fetching apk /Vysor-release.apk
Installing Vysor APK...
apk size: 4322329
TypeError: Cannot read property 'send' of undefined
TypeError: Cannot read property 'send' of undefined
web install failed TypeError: Cannot read property 'send' of undefined
falling back to asar install

**Comment by koush** [comment]
What browser is this?

**Comment by koush** [comment]
Resolved in 3.1.3. Please confirm.

**Comment by JonYeeY** [comment]
Vysor client to Vysor Client and the problem is still here.
And yes im on 3.1.3

**Comment by koush** [comment]
Generate a bug report after seeing the error please.

**Comment by JonYeeY** [comment]
Done

**Comment by koush** [comment]
You need to attach the bug report.

**Comment by JonYeeY** [comment]
process.versions {"node":"12.13.0","v8":"8.0.426.27-electron.0","uv":"1.32.0","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"76","nghttp2":"1.39.2","napi":"5","llhttp":"1.1.4","http_parser":"2.8.0","openssl":"1.1.0","icu":"65.1","unicode":"12.1","electron":"8.3.0","chrome":"80.0.3987.165"}
package.json 3.1.8
runtime package.json 3.1.4
os win32
electron true
pwa false
starting GtcRtcManger
https://vysorelectron.clockworkmod.com/#/
enterprise cache not licensed
subscription found [object Object]
clockwork cache licensed
[object RTCSessionDescription]
candidate [object RTCIceCandidate]
candidate [object RTCIceCandidate]
candidate [object RTCIceCandidate]
candidate [object RTCIceCandidate]
candidate [object RTCIceCandidate]
done sending ice candidates
remote candidate [object Object]
remote candidate [object Object]
remote candidate [object Object]
remote candidate [object Object]
remote candidate [object Object]
got rtc pinger
sending challenge response [object Object]

**Comment by koush** [comment]
Can you try checking again on the latest version?

**Comment by JonYeeY** [comment]
now i have this
![Vysor Error](https://user-images.githubusercontent.com/53002243/94059320-88eea980-fde2-11ea-9d91-ce8708e3d323.png)

**Comment by koush** [comment]
This should be fixed, please verify.

**Comment by koush** [comment]
3.2.20

**Comment by JonYeeY** [comment]
mh the bug from the start

**Comment by JonYeeY** [comment]
![error](https://user-images.githubusercontent.com/53002243/94062585-2a77fa00-fde7-11ea-9a35-3f768c09d20f.png)

**Comment by koush** [comment]
These logs indicate some kind of firewall or vpn, is that the case?

**Comment by koush** [comment]
Please generate another bug report with the error too.
