### ISSUE TITLE
International Keyboard Refactor Rollup Bug

### ISSUE THREAD

**Issue by dieskim** [koush/vysor.io#684]
**Describe the bug**
With the latest version of Vysor the International Keyboard option was moved from Global Vysor settings to the per device settings, there now seems to be another bug.

1. When I trying to type in Chinese it no longer works at all.
2. When typing in Arabic it works in some ways but not all data is sent - Arabic ligatures info is not being transferred

**To Reproduce Chinese**
1. Add Chinese input to Mac - "Pinyin - Simplified"
2. Enable International Keyboard on Vysor
3. Pick Chinese Input on Mac
4. Type "nihao" on keyboard 
5. Hit Space
6. "nihao" english latin characters are sent to device

**Expected behavior for Chinese**
1. You should be shown the Chinese Character Picker and then be able to pick characters - see screenshots
2. The Characters your pick should be sent in this case -> "你好"

**Chinese Screenshots**
OLD VERSION with picker:
![old version](https://user-images.githubusercontent.com/9603625/103603677-c2869300-4f41-11eb-8d56-3e8e9b2cadd1.jpg)

NEW VERSION without picker:
![new version](https://user-images.githubusercontent.com/9603625/103603666-ba2e5800-4f41-11eb-90a4-d5e7717a9bfd.jpg)

**To Reproduce Arabic**
1. Add Arabic input to Mac - "Arabic - QWERTY"
2. Enable International Keyboard on Vysor
3. Pick Arabic Input on Mac
4. Type "\ followed by i" on keyboard 
5. "ي" Arabic character is sent to device

**Expected behavior for Arabic**
1. The Arabic ligature character should be sent - in this case -> "ئ"
2. You can type the same "\ followed by i" on your mac screen in chrome or somewhere and see how the character differs 

More Examples:
ؤ = \ followed by u.
 
ئ = \ followed by i.
 
أ = \ followed by a.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Vysor Version 4.0.13

**iOS/Android (please complete the following information):**
 - Device: Xiaomi Mi A3
 - OS: Android 10

**Comment by koush** [comment]
Did these character picker keyboards actually work? Because from what I gather, I don't think it ever did. I believe the picker showed up, but I'm not sure it ever sent the right key presses across. The pickers seem to delete/add characters as they are pressed and then modified/picked, which I don't think Vysor would have handled properly.

**Comment by dieskim** [comment]
Yes both chinese and arabic worked fine before. I used them both
extensively before, many hours a day. That is also how I found the other
international keyboard bug https://github.com/koush/vysor.io/issues/664

**Comment by koush** [comment]
I found out that the embed for the pepper decoder is what used to unknowingly allow the character picker to pop up. This also explains why other decoders do not work, as they do not use the embed. The pepper decoder will likely be removed as well when WebCodec comes around.
The regression happened because the embed was change to no longer accept pointer events, which seems to also effect focus and receiving key strokes.
Currently trying to determine how to accept character input (ie, popping the picker) without having a clunky input field.

**Comment by koush** [comment]
Anyways, it was pure dumb luck that character pickers worked at all.

**Comment by dieskim** [comment]
ok good to know that you found what is happening

**Comment by koush** [comment]
Fix in progress.

**Comment by koush** [comment]
Fixed in 4.0.22 please confirm. I only use the standard keyboard and am not really qualified to tell if it's working. Seems fine now though? the multi character input works.

**Comment by dieskim** [comment]
just tried it
- it does look like these input issues for character picker and Arabic encoding are now working. Thanks

One new issue is now what I like to call "double paste" 
1. Copy anything on the Mac Side
2. Paste on the Android Vysor side - It will paste the same text twice

- ill keep using it and report back in a few hours

**Comment by koush** [comment]
Fixed in .23 and also fixed the context menu popping up bug.

**Comment by dieskim** [comment]
that looks better now. Ill keep testing here as well as seeing if the #664 is fixed now also.
Thanks

**Comment by Heretushi** [comment]
Hello @koush , can confirm after a couple days of testing that https://github.com/koush/vysor.io/issues/555 is clearly not fixed. I had the bug a couple times a day.

**Comment by koush** [comment]
@Heretushi thanks I’ve reopened it. Was hoping this issue had resolved it, as it uncovered some bugs where it shouldn’t have been working at all in a lot of cases.
