### ISSUE TITLE
request a refund

### ISSUE THREAD

**Issue by hh770718** [koush/vysor.io#802]
I purchased a lifetime subscription (<24 hours) and I want to get a service refund because the product does not meet my expectations and is severely delayed and unable to operate.

I tried (<24 hours) to send a refund request email to billing@vysor.io, and I received an automatic reply email. But I haven't received any reply, I don't know if it has been refunded.

I want a refund, thank you.

Pay by credit card
email: hh770718@yahoo.com.tw

**Comment by hh770718** [comment]
Hello, I purchased Vysor pro on June 8th. I requested a refund within 24 hours, but I only received an automatic reply letter, and I haven’t received any reply until now.

**Comment by koush** [comment]
I fixed the delay bug.

**Comment by hh770718** [comment]
I still have a lag problem during operation, and the higher the image quality, the more serious it is. Compared with the version before June 6th, there is no such problem. Isn't an unconditional refund within 24 hours after the purchase of the Pro version? The purchase instructions did not say that it was a conditional refund. It only stated that the first purchase can be refunded within 24 hours after the purchase, and I am also the first purchase.
[https://support.vysor.io/billing/refund/](url)

**Comment by koush** [comment]
There's no purchase for the email hh770718@yahoo.com.tw

**Comment by koush** [comment]
found it and refunded
