### ISSUE TITLE
Slow after andriod 10 update

### ISSUE THREAD

**Issue by Therepup** [koush/vysor.io#879]
https://gist.github.com/b8dc83462a6a70fa9b92b802a458231f
https://prnt.sc/1gpsisp
https://prnt.sc/1gpsq6x
zte 2050
android 10
gpu radeon rx 570 8gb
Processor AMD FX-8320E Eight-Core Processor                 3.20 GHz
Installed RAM	16.0 GB

**Comment by koush** [comment]
thanks taking a look

**Comment by koush** [comment]
Just to be certain, please try restarting your computer and phone as well.

**Comment by koush** [comment]
After restarting, also try the following decoders:

WebCodec Hardware + Fallback
and
WebAssembly

**Comment by Therepup** [comment]
Neither of those option worked is still mega slow

**Comment by koush** [comment]
Can you verify this is happening on the 4.1.70 update I released yesterday? Another user confirmed it fixed. https://github.com/koush/vysor.io/issues/882

You may need to click "Defaults" in Vysor's device settings.

**Comment by Therepup** [comment]
How do I update the vysor? Mines is still in 4.1.62

**Comment by Therepup** [comment]
Never mind the runtime is  .62 the version is .70 it still happening.

**Comment by koush** [comment]
You restored to defaults and retried the different decoders?

**Comment by Therepup** [comment]
I did restore default and tried all the decoders yes

**Comment by koush** [comment]
Can you make a video of what the performance looks like? Screen recording?

**Comment by Therepup** [comment]
https://www.youtube.com/watch?v=DW2NICOAQnI

**Comment by koush** [comment]
I think this might be fixed in v4.1.92 (Runtime v4.1.77)
